# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: feather 0.4.2 ruby lib

Gem::Specification.new do |s|
  s.name = "feather"
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Scott Tadman"]
  s.date = "2016-03-28"
  s.description = "A simple light-weight text templating system"
  s.email = "github@tadman.ca"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "RELEASES.txt",
    "Rakefile",
    "VERSION",
    "feather.gemspec",
    "lib/feather.rb",
    "lib/feather/support.rb",
    "lib/feather/template.rb",
    "notes/example.ft",
    "test/helper.rb",
    "test/test_feather.rb",
    "test/test_feather_support.rb",
    "test/test_feather_template.rb"
  ]
  s.homepage = "http://github.com/twg/feather"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Light-weight text tempating system"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
    else
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
    end
  else
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
  end
end

